Traceback (most recent call last):
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/jordivilla/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#taken from https://wellsr.com/python/how-to-create-custom-modules-in-python/

import module1

module1.print_text()

print("This message is from the main file")

log16 = module1.find_log(16)
print(log16)

exp16 = module1.find_exp(16)
print(exp16)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;66;03m#taken from https://wellsr.com/python/how-to-create-custom-modules-in-python/[39;00m
[0;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mmodule1[39;00m
[1;32m      5[0m module1[38;5;241m.[39mprint_text()
[1;32m      7[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mThis message is from the main file[39m[38;5;124m"[39m)

File [0;32m~/GitHub/Tools/teachingTools/module1.py:2[0m
[1;32m      1[0m [38;5;66;03m# example taken from https://wellsr.com/python/how-to-create-custom-modules-in-python/[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      4[0m [38;5;28;01mdef[39;00m [38;5;21mprint_text[39m():
[1;32m      5[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mThis message is from an external module[39m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'numpy'

