Traceback (most recent call last):
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/jordivilla/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
!wget -P dataDownload -nc https://ftp.ncbi.nlm.nih.gov/geo/series/GSE160nnn/GSE160306/suppl/GSE160306_human_retina_DR_totalRNA_counts.txt.gz
import GEOparse
gse = GEOparse.get_GEO("GSE160306",destdir="./dataDownload")
------------------

----- stdout -----
El fitxer â€˜dataDownload/GSE160306_human_retina_DR_totalRNA_counts.txt.gzâ€™ ja existeix, no es baixa.
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m get_ipython()[38;5;241m.[39msystem([38;5;124m'[39m[38;5;124mwget -P dataDownload -nc https://ftp.ncbi.nlm.nih.gov/geo/series/GSE160nnn/GSE160306/suppl/GSE160306_human_retina_DR_totalRNA_counts.txt.gz[39m[38;5;124m'[39m)
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mGEOparse[39;00m
[1;32m      3[0m gse [38;5;241m=[39m GEOparse[38;5;241m.[39mget_GEO([38;5;124m"[39m[38;5;124mGSE160306[39m[38;5;124m"[39m,destdir[38;5;241m=[39m[38;5;124m"[39m[38;5;124m./dataDownload[39m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'GEOparse'

